import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("cleaned_care_transition.csv")
df['Date'] = pd.to_datetime(df['Date'])
st.header("Care Transition Efficiency and Placement Outcome Analytics")
st.subheader("Key Performance Indicators")
col1,col2,col3,col4,col5=st.columns(5)
col1.metric("Transfer Efficiency",round(df["Transfer_Efficiency"].mean(),2))
col2.metric("Discharge Effectiveness",round(df['Discharge_Effectiveness'].mean(),2))
col3.metric("Throughput",round(df['Throughput'].mean(),2))
col4.metric("Backlog",int(df["Backlog"].mean()))
col5.metric("Outcome Stability",round(df["outcome_stability"].mean(),2))
st.sidebar.header("Filters")
start_date=st.sidebar.date_input("Start date",df['Date'].min())
end_date=st.sidebar.date_input("End date",df['Date'].max())
filtered_df=df[(df['Date']>=pd.to_datetime(start_date)) & (df['Date']<=pd.to_datetime(end_date))]
st.subheader("Transfer Effectiveness over time")
fig,ax=plt.subplots(figsize=(15,5))
ax.plot(filtered_df['Date'],filtered_df['Transfer_Efficiency'])
ax.set_xlabel("Date")
ax.set_ylabel("Transfer_Efficiency") 	
st.pyplot(fig)
st.write("Transfer efficiency shows fluctuations indicating inconsistent CBP to HHS transitions.")
st.subheader("Discharge Effectiveness")
fig,ax=plt.subplots(figsize=(15,5))
ax.plot(filtered_df["Date"],filtered_df['Discharge_Effectiveness'])
ax.set_xlabel("Date")
ax.set_ylabel("Discharge_Effectiveness")
st.pyplot(fig)
st.write("Discharge effectiveness shows fluctuations and remains relatively low, suggesting slower sponsor placements.")
st.subheader("Backlog Trend")
fig,ax=plt.subplots(figsize=(15,5))
ax.plot(filtered_df["Date"],filtered_df['Backlog'])
ax.set_xlabel("Date")
ax.set_ylabel("Backlog Trend")
st.pyplot(fig)
st.write("Backlog trends indicate accumulation of cases in HHS care.with fluctuations and gradual decrease observed in 2025")
st.subheader("Outcome Stability")
fig,ax=plt.subplots(figsize=(15,5))
ax.plot(filtered_df["Date"],filtered_df["outcome_stability"])
ax.set_xlabel("Date")
ax.set_ylabel("outcome_stability")
st.pyplot(fig)
st.write("Outcome stability highlights variability in discharge performance rolling over 7 days.")

